name: Check Quotes Validity
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check all rango routes valid
        id: check-routes
        run: python src/check.py
        shell: bash
        env:
          RANGO_API_KEY: ${{ secrets.RANGO_API_KEY }}
          UPTIME_ROBOT_API_KEY: ${{ secrets.UPTIME_ROBOT_API_KEY }}
